---
title: "SSECR exploratory plots"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
librarian::shelf(ggplot2, cowplot, dplyr, emmeans)
data <- read.csv("~/data/raw_data/NEON_PRIN/NEON_PRIN_intermediate.csv")

```


## Variables
### Correlations
```{r corrplot, out.width="60%", echo=FALSE, warning=FALSE, message = FALSE}
predictor_cor <- cor(data[c(6,9:14)], use="complete.obs") # correlation matrix
library(corrplot)
corrplot(predictor_cor,
         method = "color", 
         addCoef.col="black", 
         order = "AOE", 
         number.cex=.75,
         type = "upper",
         tl.cex = .75,
         tl.col = "black")
```

### Timeseries
```{r timeseries, fig.show="hold", out.width="50%", echo=FALSE, warning=FALSE}
ggplot(data, aes(x=YEAR,y=SIZE, color = SCI_NAME))+
  geom_point(alpha = .25) +
  theme_cowplot() +
  theme(legend.position = "none")

ggplot(data, aes(x=YEAR, y=mean_daily_temp))+
  geom_point(color="darkred") +
  ylab("MEAN DAILY TEMP") +
  scale_x_continuous(labels = function(x) x -1) +
  theme_cowplot()

ggplot(data, aes(x=YEAR, y=annual_avg_DO))+
  geom_point(color="navy") + 
  ylab("ANNUAL AVG. DO") +
  scale_x_continuous(labels = function(x) x -1) +
  theme_cowplot()
```

## Individual level
### Temperature
```{r temp size, fig.show="hold", out.width="60%", echo=FALSE, warning=FALSE, message = FALSE}
ggplot(data,aes(x=mean_daily_temp, y=SIZE))+
  geom_point(aes(color = SCI_NAME), alpha = .25)+
  geom_smooth(aes(color = SCI_NAME), method=lm,se=F)+
  geom_smooth(color = "black", linetype = "dashed", method=lm,se=F)+
  xlab("MEAN DAILY TEMP") +
  theme_cowplot() +
  theme(legend.position = "none")

```

#### Model-estimated temp effect (accounting for DO)
```{r temp do size, fig.show="hold", out.width="60%", echo=FALSE, warning=FALSE, message = FALSE}
do_temp_size_model <- lm(log(SIZE) ~ mean_daily_temp * annual_avg_DO, data)
predict_size_temp <- data.frame(emmeans(do_temp_size_model, ~mean_daily_temp * annual_avg_DO, 
                                   at=list(mean_daily_temp=c(15.5, 16, 16.5,17, 17.5))), type = "response")
ggplot(predict_size_temp,aes(x=mean_daily_temp, y=emmean))+
  geom_line(color = "darkred", linewidth =1) +
  geom_ribbon(data = predict_size_temp, aes(ymin=lower.CL, ymax=upper.CL), alpha = .25, fill = "darkred") +
  geom_ribbon(data = predict_size_temp, aes(ymin=lower.CL, ymax=upper.CL), alpha = .25, fill = "darkred") +
  xlab("MEAN DAILY TEMP") +
  ylab("SIZE") +
  theme_cowplot() +
  theme(legend.position = "none")
```

### Dissolved oxygen
```{r DO size, fig.show="hold", out.width="60%", echo=FALSE, warning=FALSE, message = FALSE}
ggplot(data,aes(x=annual_avg_DO, y=SIZE))+
  geom_point(aes(color = SCI_NAME), alpha = .25)+
  geom_smooth(aes(color = SCI_NAME), method=lm,se=F)+
  geom_smooth(color = "black", linetype = "dashed", method=lm,se=F)+
  xlab("ANNUAL AVG. DO") +
  theme_cowplot() +
  theme(legend.position = "none")

```

#### Model-estimated DO effect (accounting for temp)
```{r DO temp size, fig.show="hold", out.width="60%", echo=FALSE, warning=FALSE, message = FALSE}
predict_size_do <- data.frame(emmeans(do_temp_size_model, ~mean_daily_temp * annual_avg_DO, 
                                   at=list(annual_avg_DO=c(8.5, 9, 9.5, 10, 10.5)), type = "response"))
ggplot(predict_size_do,aes(x=annual_avg_DO, y=response))+
  geom_line(color = "navy", linewidth =1) +
  geom_ribbon(data = predict_size_do, aes(ymin=lower.CL, ymax=upper.CL), alpha = .25, fill = "navy") +
  geom_ribbon(data = predict_size_do, aes(ymin=lower.CL, ymax=upper.CL), alpha = .25, fill = "navy") +
  xlab("ANNUAL AVG. DO") +
  ylab("SIZE") +
  theme_cowplot() +
  theme(legend.position = "none")
```

## Population level
### Temperature
```{r pop temp, fig.show="hold", out.width="60%", echo=FALSE, warning=FALSE, message = FALSE}
pop <- data %>% 
  group_by(DATE, EFFORT) %>%
  dplyr::count(SP_CODE) # count of species by date and electrofishing pass
pop$EFFORT_h <- pop$EFFORT / 3600 # sec to hr
pop$CPUE <- pop$n / pop$EFFORT_h
subset <- data %>%
  select(!c(SIZE)) %>%
  distinct()
pop <- pop %>% merge(subset, by=c("DATE", "EFFORT", "SP_CODE"), all = T)

ggplot(pop,aes(x=mean_daily_temp, y=CPUE))+
  geom_point(aes(color = SCI_NAME), alpha = .25)+
  geom_smooth(aes(color = SCI_NAME), method=lm,se=F)+
  geom_smooth(color = "black", linetype = "dashed", method=lm,se=F)+
  xlab("MEAN DAILY TEMP") +
  theme_cowplot() +
  theme(legend.position = "none")

```

### Dissolved oxygen
```{r pop do, fig.show="hold", out.width="60%", echo=FALSE, warning=FALSE, message = FALSE}
ggplot(pop,aes(x=annual_avg_DO, y=CPUE))+
  geom_point(aes(color = SCI_NAME), alpha = .25)+
  geom_smooth(aes(color = SCI_NAME), method=lm,se=F)+
  geom_smooth(color = "black", linetype = "dashed", method=lm,se=F)+
  xlab("ANNUAL AVG. DO") +
  theme_cowplot() +
  theme(legend.position = "none")

```




